### PR TITLE
Make Getting Started options

### PR DESCRIPTION
**Pull request by jjcarstens**
Adds 3 getting started options:

* Try it Out
* Build an Example
* Full DIY

We initially discussed just the 2 options, but I thought throwing in the examples here might be worthwhile. I'm not attached to visuals or wording and open to suggestions

image

### CODE REVIEW

**Comment by fhunleth** [comment]
That's a great idea! I like the 3 options.

While the icons definitely look good for the theme, is there a way to have a mini-screenshot? I think that many people won't know what Livebook is, but having a little screenshot of the Livebook webpage next to a Pi or something like that might help. I'm less sure what the pictures of the examples and full DIY look like. They're both terminal windows to me, but maybe one is a NervesMOTD window and the other is a terminal window with `mix nerves.new my_project` or something like that?

**Comment by jjcarstens** [comment]
Works for me. I'll adjust

**Review by mnishiguchi — APPROVED** [review]

**Comment by jjcarstens** [comment]
@fhunleth Thoughts on this layout instead?
image

**Comment by fhunleth** [comment]
I love it!!!!

**Review by fhunleth — APPROVED** [review]

**Comment by jjcarstens** [comment]
Added the NervesMOTD image:
image

**Review by fhunleth — COMMENTED** [review]
We should release a new version of MOTD that puts units on the CPU temperature. It's Celsius. Not sure why that bothers me....

**Comment by jjcarstens** [comment]
We should do that...but if you like having the image there too, I'll just add C° in post here so we can move this along 😂

**Comment by fhunleth** [comment]
I like post. Also  °C.  :joy:

**Pull request merged**
